# Generated by Django 3.2.8 on 2021-10-19 15:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.TextField()),
                ('data_criacao', models.DateField(auto_now=True)),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Bioc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioc.post')),
            ],
        ),
    ]
