# Generated by Django 3.2.8 on 2021-10-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioc', '0002_auto_20211019_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caract',
            field=models.CharField(default='0', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='cores',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.FileField(default='0', upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='sobre',
            field=models.CharField(default='0', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='tamanho',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
