# Generated by Django 3.2.8 on 2021-10-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioc', '0004_auto_20211019_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugestao', models.TextField()),
                ('recado', models.TextField()),
                ('categoria', models.CharField(max_length=50)),
                ('foto', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.FileField(default='empty', upload_to=''),
        ),
    ]
