# Generated by Django 3.2.8 on 2021-10-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioc', '0006_post_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucu',
            name='post',
        ),
        migrations.DeleteModel(
            name='Fito',
        ),
        migrations.DeleteModel(
            name='Sucu',
        ),
    ]
