# Generated by Django 3.2.8 on 2021-10-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioc', '0011_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
