# Generated by Django 3.2.8 on 2021-11-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioc', '0012_delete_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.FileField(upload_to='media/%Y/%m/%d/'),
        ),
    ]
