# Generated by Django 3.2.8 on 2021-11-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioc', '0013_alter_post_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.FileField(upload_to='%Y/%m/%d/'),
        ),
    ]
