# Generated by Django 3.2.8 on 2021-11-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioc', '0015_auto_20211124_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='tipo',
            new_name='categoria',
        ),
    ]
